"""Add authentication models

Revision ID: 979e418b9540
Revises: 
Create Date: 2025-06-26 23:52:04.295010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979e418b9540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('allowed_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('added_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_admin_id'], ['user.id'], name='fk_allowed_user_added_by_admin_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowed_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_user_email'), ['email'], unique=True)

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_meeting_created_by_user_id', 'user', ['created_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meeting_created_by_user_id', type_='foreignkey')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('allowed_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_user_email'))

    op.drop_table('allowed_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
